import type { Question } from '@/types/assessment'

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    step: 1,
    type: 'single-select',
    question: 'What is your age range?',
    subtext: "This helps us tailor ingredient recommendations to your skin's changing needs.",
    required: true,
    options: [
      { value: 'under-18', label: 'Under 18' },
      { value: '18-24', label: '18 – 24' },
      { value: '25-34', label: '25 – 34' },
      { value: '35-44', label: '35 – 44' },
      { value: '45-54', label: '45 – 54' },
      { value: '55+', label: '55 and above' },
      { value: 'prefer-not', label: 'Prefer not to say', isNotSure: true },
    ],
  },
  {
    id: 'q2',
    step: 2,
    type: 'single-select',
    question: 'How would you describe your skin type?',
    subtext: 'Select the option that best describes your skin on most days.',
    required: true,
    options: [
      { value: 'dry', label: 'Dry — feels tight, sometimes flaky' },
      { value: 'oily', label: 'Oily — shiny by midday, enlarged pores' },
      { value: 'combination', label: 'Combination — oily T-zone, normal or dry cheeks' },
      { value: 'sensitive', label: 'Sensitive — reacts easily, gets red or irritated' },
      { value: 'normal', label: 'Normal — balanced, no major concerns' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q3',
    step: 3,
    type: 'multi-select',
    question: 'What are your main skin concerns?',
    subtext: 'Select up to 3 concerns.',
    required: true,
    maxSelections: 3,
    options: [
      { value: 'acne', label: 'Acne / breakouts' },
      { value: 'dryness', label: 'Dryness / dehydration' },
      { value: 'pih', label: 'Dark spots / hyperpigmentation' },
      { value: 'uneven-tone', label: 'Uneven tone / dullness' },
      { value: 'aging', label: 'Fine lines / aging' },
      { value: 'oiliness', label: 'Excess oil / shine' },
      { value: 'sensitivity', label: 'Sensitivity / redness' },
      { value: 'pores', label: 'Large pores' },
      { value: 'sun-protection', label: 'Sun protection' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q4',
    step: 4,
    type: 'single-select',
    question: 'How severe is your top skin concern?',
    subtext: 'This helps us understand the level of care you need.',
    required: true,
    branchKey: 'severity',
    options: [
      { value: 'mild', label: 'Mild — occasional, does not bother me much' },
      { value: 'moderate', label: 'Moderate — noticeable, I want to address it' },
      { value: 'severe', label: 'Severe — daily struggle, I need real help' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q5',
    step: 5,
    type: 'single-select',
    question: 'What is your main skincare goal right now?',
    required: true,
    options: [
      { value: 'treat', label: 'Treat a specific condition (acne, dark spots, etc.)' },
      { value: 'maintain', label: 'Maintain healthy skin / prevention' },
      { value: 'anti-aging', label: 'Anti-aging — firmness and fine lines' },
      { value: 'brightening', label: 'Brightening and even skin tone' },
      { value: 'simple', label: 'Build a simple, effective daily routine' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q6',
    step: 6,
    type: 'slider',
    question: 'How sensitive is your skin?',
    subtext: "Slide to the number that best describes your skin's reactivity.",
    required: true,
    branchKey: 'sensitivity',
    range: {
      min: 1,
      max: 5,
      minLabel: 'Not sensitive',
      maxLabel: 'Very sensitive',
    },
  },
  {
    id: 'q7',
    step: 7,
    type: 'multi-select',
    question: 'Do you have any known ingredient allergies?',
    subtext: 'Select all that apply. We will exclude these from your routine.',
    required: false,
    options: [
      { value: 'none', label: 'No known allergies' },
      { value: 'fragrance', label: 'Fragrance / perfume' },
      { value: 'retinol', label: 'Retinol / retinoids' },
      { value: 'aha', label: 'AHA / glycolic acid' },
      { value: 'salicylic', label: 'Salicylic acid' },
      { value: 'parabens', label: 'Parabens' },
      { value: 'nut-oils', label: 'Nut oils (e.g. shea, argan)' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q8',
    step: 8,
    type: 'radio',
    question: 'Are you currently pregnant or breastfeeding?',
    subtext: 'This affects which ingredients are safe to recommend.',
    required: true,
    branchKey: 'pregnancy',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'prefer-not', label: 'Prefer not to say', isNotSure: true },
    ],
  },
  {
    id: 'q9',
    step: 9,
    type: 'radio',
    question: 'Are you currently using any prescription skincare treatments?',
    subtext: 'For example: Tretinoin, Accutane, or prescription antibiotics.',
    required: true,
    branchKey: 'prescription',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q10',
    step: 10,
    type: 'single-select',
    question: 'Which climate do you live in?',
    subtext: 'Climate affects which textures and formulas work best for your skin.',
    required: true,
    options: [
      { value: 'hot-humid', label: 'Hot & humid (e.g. Kampala, Lagos, Mombasa)' },
      { value: 'hot-dry', label: 'Hot & dry (e.g. Nairobi during dry season)' },
      { value: 'cool', label: 'Cool / temperate' },
      { value: 'indoor-ac', label: 'Mostly indoors in air-conditioning' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q11',
    step: 11,
    type: 'single-select',
    question: 'How much direct sunlight do you get each day?',
    required: true,
    options: [
      { value: 'under-30', label: 'Under 30 minutes' },
      { value: '30-2hr', label: '30 minutes to 2 hours' },
      { value: 'over-2hr', label: 'More than 2 hours' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q12',
    step: 12,
    type: 'single-select',
    question: 'How would you describe your current skincare routine?',
    required: true,
    options: [
      { value: 'none', label: 'I do not have one — starting from scratch' },
      { value: 'basic', label: 'Basic — cleanser and moisturizer only' },
      { value: 'established', label: 'Established — a few targeted products' },
      { value: 'extensive', label: 'Extensive — 5 or more steps daily' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q13',
    step: 13,
    type: 'single-select',
    question: 'What is your monthly skincare budget?',
    required: true,
    options: [
      { value: 'under-100k', label: 'Under 100,000 UGX' },
      { value: '100k-200k', label: '100,000 – 200,000 UGX' },
      { value: '200k-300k', label: '200,000 – 300,000 UGX' },
      { value: 'over-300k', label: '300,000+ UGX' },
      { value: 'no-limit', label: 'No budget limit' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q14',
    step: 14,
    type: 'single-select',
    question: 'Do you prefer natural or clinically active ingredients?',
    required: true,
    options: [
      { value: 'natural', label: 'Strongly prefer natural and organic' },
      { value: 'mixed', label: 'A mix of natural and clinical actives' },
      { value: 'clinical', label: 'Prefer clinically proven active ingredients' },
      { value: 'no-pref', label: 'No preference — whatever works best' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q15',
    step: 15,
    type: 'single-select',
    question: 'How does your skin feel about an hour after washing?',
    subtext: 'This reveals your true hydration needs.',
    required: true,
    options: [
      { value: 'very-tight', label: 'Very tight and dry' },
      { value: 'slightly-dry', label: 'Slightly dry or uncomfortable' },
      { value: 'comfortable', label: 'Comfortable and balanced' },
      { value: 'oily', label: 'Oily or shiny in places' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q16',
    step: 16,
    type: 'multi-select',
    question: 'Have you experienced any negative skin reactions before?',
    subtext: 'Select all that have happened.',
    required: false,
    options: [
      { value: 'none', label: 'No, never' },
      { value: 'redness', label: 'Redness or irritation from products' },
      { value: 'breakouts', label: 'Breakouts caused by products' },
      { value: 'burning', label: 'Burning or stinging sensation' },
      { value: 'peeling', label: 'Excessive peeling or flaking' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q17',
    step: 17,
    type: 'single-select',
    question: 'What product texture do you prefer?',
    required: true,
    options: [
      { value: 'lightweight', label: 'Lightweight — fast-absorbing, no residue' },
      { value: 'rich', label: 'Rich and creamy — deeply nourishing' },
      { value: 'gel', label: 'Gel — cooling and refreshing' },
      { value: 'oil', label: 'Oil-based — luxurious and natural' },
      { value: 'no-pref', label: 'No preference' },
      { value: 'not-sure', label: 'Not sure', isNotSure: true },
    ],
  },
  {
    id: 'q18',
    step: 18,
    type: 'radio',
    question: 'One last step before we reveal your routine.',
    subtext:
      'The personalised routine generated by this assessment is for informational purposes only and is not a substitute for professional medical advice. Your Skin Care Adviser reviews all recommendations before they are finalised.',
    required: true,
    options: [
      {
        value: 'confirm',
        label: 'I understand — show me my personalised routine',
      },
    ],
  },
]

export const TOTAL_STEPS = QUESTIONS.length
export const NOT_SURE_THRESHOLD = 3
